---

repos:

- repo: https://github.com/Kintyre/ksconf
  rev: v0.9.0
  hooks:
    - id: ksconf-check
    - id: ksconf-sort
    - id: ksconf-xml-format

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
    - id: trailing-whitespace
      exclude: README\.md
    - id: end-of-file-fixer
      exclude: (README\.md|\.bumpversion.cfg)$
    - id: check-json
    - id: check-xml
    - id: check-ast
    - id: check-added-large-files
      args: [ "50" ]
    - id: check-merge-conflict
    - id: mixed-line-ending
      args: [ '--fix=lf' ]
